# Generated by Django 4.2.9 on 2024-02-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0002_alter_movies_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movie_app.category"
            ),
        ),
        migrations.AlterField(
            model_name="movies",
            name="slug",
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="title",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
